SELECT a.NOME_ALUNO, c.NOME_CURSO FROM TBALUNO AS a
INNER JOIN TBMATRICULA AS m   ON a.ID_ALUNO =  m.ALUNO_ID  
INNER JOIN TBCURSO AS c ON c.ID_CURSO =  m.CURSO_ID 
ORDER BY NOME_CURSO


SELECT a.NOME_ALUNO, c.ID_CURSO FROM TBALUNO AS a 
INNER JOIN TBMATRICULA AS m  
ON a.ID_ALUNO = m.ALUNO_ID  
INNER JOIN TBCURSO AS c 
ON c.ID_CURSO = m.CURSO_ID  WHERE c.ID_CURSO = 5 AND SEXO = 'F'